[features]
seeds = false
skip-lint = false
[programs.localnet]
my_solana_program = "GxgudfRVS2fdXJ2LWEXCg7y8HUH531xNHMn4hviF77Zh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/omarbenharbit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
